### ISSUE TITLE
apt cache update fails on gcp with debian 11

### ISSUE THREAD

**Issue by autonompost** [autonompost/whisper-autotranscription#10]
`TASK [sysupdate : Perform a dist-upgrade.] *************************************
fatal: [35.204.172.121]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details., E:Repository '
https://packages.cloud.google.com/apt cloud-sdk-bullseye InRelease' changed its 'Origin' value from 'cloud-sdk-bullseye' to 'namespaces/google.com:cloudsdktool/repositories/cloud-sdk-bullseye', E:Repository 'https://packages.cloud.
google.com/apt cloud-sdk-bullseye InRelease' changed its 'Label' value from 'cloud-sdk-bullseye' to 'namespaces/google.com:cloudsdktool/repositories/cloud-sdk-bullseye'"}`

**Comment by autonompost** [comment]
workaround

```
- name: Recursively remove directory
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/google-cloud.list
    state: absent

- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: yes
    update_cache: true
    cache_valid_time: 86400 # 1 day
```

**Comment by autonompost** [comment]
workaround

```
- name: remove google cloud repo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/google-cloud.list
    state: absent

- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: yes
    update_cache: true
    cache_valid_time: 86400 # 1 day
```
